//
// Created by Krzysiek on 2019-08-24.
//

#ifndef ESP_COMMUNICATION_H
#define ESP_COMMUNICATION_H

#define TCP_ERROR_NO_RESPONSE 0xE0
#define TCP_SUCCESS 0xA0

#define UART_BUFFER_SIZE 100
#define UART_BUFFER_OVERFLOW 0xEF

#define FLAG_UART_RECEIVING (1 << 0)

#endif //ESP_COMMUNICATION_H
